
global:
  imageRegistry: "set-me"
  imagePullSecrets: []

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    seccompProfile:
      type: "RuntimeDefault"

  securityContext: 
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - "ALL"
  
  resources:
    requests:
      cpu: "100m" 
      memory: "128Mi"
    limits:
      cpu: "500m" 
      memory: "256Mi"
  
  secrets:
    amqp: 
      name: "set-me"
      username: "set-me"
      password: "set-me"
    objectStorage:
      s3: 
        name: "set-me"
        endpoint_url: "set-me"
        access_key: "set-me"
        secret_key: "set-me"
        region: "set-me"


rabbitmq:
  clusterName: "set-me"
  vhost: ""